### ISSUE TITLE
У примеров в FF странно работают алерты при нажатии кнопки Выполнить http://learn.javascript.ru/bind

### ISSUE THREAD

**Issue by konstantin-agafonov** [iliakan/javascript-tutorial#10]
![Image 1](http://s22.postimg.org/gpm6rkl35/image.jpg)

![Image 2](http://s22.postimg.org/a0fnbjzr5/image.jpg)

![Image 3](http://s22.postimg.org/65c98zgld/image.jpg)

**Comment by iliakan** [comment]
Очень странно, в последней альфе FF всё ок.

**Comment by iliakan** [comment]
closed due to inactivity, couldn't reproduce.
