### ISSUE TITLE
Добавить комментирий в статье #Как писать неподдерживаемый код?

### ISSUE THREAD

**Issue by ArmGono** [iliakan/javascript-tutorial#106]
http://learn.javascript.ru/write-unmain-code
Необходимо для новичков добавить комментарий, что данная статья является примером того, что нельзя делать. 
Данный текст надо выделить в начале или в конце статьи, т.к. она интересная и смешная для раработчиков, но вводит в заблуждение новичков, которые читают данную книгу.

**Comment by NugzarGaguliya** [comment]
Не стоит подменять понятия новичёк в программировании и человек, лишённый чувства иронии.
Ваш issue мне напомнил историю про кошку и микроволновку.

**Comment by iliakan** [comment]
Ну, всё люди понимают, просто не сразу. Тем продуктивнее процесс осознания.
