### ISSUE TITLE
Текст не до конца, не работает пример

### ISSUE THREAD

**Issue by golovewkin** [iliakan/javascript-tutorial#133]
Скажи пожалуйста, почему тут
https://github.com/iliakan/javascript-tutorial/blob/ru/4-ajax/10-ajax-jsonp/article.md
текст не до конца?

В самом учебнике
https://learn.javascript.ru/ajax-jsonp
не работает последний пример

**Comment by iliakan** [comment]
1) Текст из-за того, что github так форматит обрезан, на самом деле он есть.
2) Поправил, спасибо.
