### ISSUE TITLE
картинки разные

### ISSUE THREAD

**Issue by golovewkin** [iliakan/javascript-tutorial#134]
Тут
https://learn.javascript.ru/metrics

По идее, какая то из них неправильная
https://ru.js.cx/article/metrics/metric-all.png
https://ru.js.cx/article/metrics/metric-scroll-top.png

**Comment by Bezart** [comment]
ага, вижу 
@iliakan где scrollTop правильно показывается?

**Comment by iliakan** [comment]
@bezart да, вторая правильная.

`scrollTop` включает в себя прокрученную часть, в том числе ту, которая за рамкой скрыта.

**Comment by iliakan** [comment]
ping? :)
