### ISSUE TITLE
Ошибка в тексте на https://learn.javascript.ru/instanceof

### ISSUE THREAD

**Issue by Sigizmund2012** [iliakan/javascript-tutorial#14]
"В проверке rabbit instanceof Rabbit, совпадение на первом же шаге этго алгоритма, так как: rabbit.__proto__ == Rabbit.prototype."  Этго надо бы на этого заменить.

**Comment by Sigizmund2012** [comment]
Странно, тутошний редактор свойство proto выделил жирным и убрал нижние подчёркивания.

**Comment by iliakan** [comment]
Это код, его нужно в символы ` оборачивать.
