### ISSUE TITLE
В главе "Наборы и диапазоны" секции "Регулярные выражения" используется квантификатор + из следующей главы

### ISSUE THREAD

**Issue by zeird** [iliakan/javascript-tutorial#162]
В [этом файле](/iliakan/javascript-tutorial/blob/ru/10-regular-expressions-javascript/4-regexp-character-sets-and-ranges/article.md#%D0%94%D0%B8%D0%B0%D0%BF%D0%B0%D0%B7%D0%BE%D0%BD%D1%8B) после слов `Например, нам нужно найти все слова в тексте. Если они на английском -- это достаточно просто:` в четырех идущих подряд регулярках используется квантификатор `+`, хотя по логике впервые он должен появляется лишь в следующей главе.
Может, изменить регулярки или добавить комментарий, что, мол, "товарищи изучающие, не пугайтесь, про то, что такое "+" будет рассказано в следующей главе"?

**Comment by iliakan** [comment]
thanks fixed.
