### ISSUE TITLE
Опечатка в секции "Методы объектов и контекст вызова" -> "Преобразование объектов: toString и valueOf"

### ISSUE THREAD

**Issue by zeird** [iliakan/javascript-tutorial#163]
В [этом файле](https://github.com/iliakan/javascript-tutorial/blob/ru/1-js/6-objects-more/2-object-conversion/article.md#%D0%98%D1%82%D0%BE%D0%B3%D0%BE) вот здесь
![](http://i.imgur.com/lB7L6lw.png)
должен быть пробел. Без него в самом курсе виден нераспарсенный комментарий `//+run`.

**Comment by iliakan** [comment]
fixed thanks.
