### ISSUE TITLE
Неточность в "Регулярные выражения" -> "Скобочные группы"

### ISSUE THREAD

**Issue by angly-cat** [iliakan/javascript-tutorial#164]
В [этом файле](https://github.com/iliakan/javascript-tutorial/blob/ru/10-regular-expressions-javascript/7-regexp-groups/article.md#%D0%92%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%8B) в первом блоке кода в комментарии сказано, что алерт выведет `<span class="my">, span, s`. Это ошибка. Предлагаю заменить на фактически выводящеемя `<span class="my">,span class="my",span,class="my"`.

**Comment by iliakan** [comment]
PR is welcome.

**Comment by slawiko** [comment]
Поправлено в #292, можно закрывать
