### ISSUE TITLE
опечатка http://learn.javascript.ru/settimeout-setinterval#setinterval

### ISSUE THREAD

**Issue by konstantin-agafonov** [iliakan/javascript-tutorial#19]
Исключением является IE, в котором таймер «застывает» во время выполнения JavaScript.

А так будет *выгляд__и__ть* картинка с рекурсивным setTimeout:

**Comment by talgautb** [comment]
```На время создания стандарта оптимальным числом показались 4мс. ```
показал**и**сь на показал**о**сь ?
