### ISSUE TITLE
Некорректно запускается пример в разделе "Примеси"

### ISSUE THREAD

**Issue by Merrell** [iliakan/javascript-tutorial#21]
В разделе http://learn.javascript.ru/mixins#примесь-для-событий
пример запускается с ошибкой (и через прямой запуск, и через песочницу) - не добавлен написанный выше код ( var eventMixin = ...)

**Comment by Merrell** [comment]
Поправилось при нажатии кнопки "выполнить", а при нажатии на "открыть в песочнице" - по-прежнему осталось с той же ошибкой (eventMixin is not defined)...

**Comment by iliakan** [comment]
Made it not runnable any more.
