### ISSUE TITLE
Возможно некорректно построено предложение

### ISSUE THREAD

**Issue by konstantin-agafonov** [iliakan/javascript-tutorial#225]
http://learn.javascript.ru/regexp-ahchors

Как есть: "Каретка ^ совпадает в начале текста, а доллар $ — в конце."

Возможно правильно "Каретка ^ совпадает С началОМ текста, а доллар $ — С концОМ."   ?

Или "Каретка ^ обозначает начало текста, а доллар $ — конец текста.""

**Comment by iliakan** [comment]
Да тут как раз фишка в совпадении проверки. То есть, тест на начало/конец строки либо проходит либо нет.

То есть, когда "каретка с началОМ не совпадает", то возможно понимание, что каретке соответствует некое начало текста, а такого как раз нет.
