### ISSUE TITLE
Новые статьи по ES6

### ISSUE THREAD

**Issue by sarkistlt** [iliakan/javascript-tutorial#230]
Илья добрый день. Очень доволен вашей книгой, спасибо за это. Я уже купил все три, и в целом это был мой фундамент в js. 
Хотелось бы так же увидеть больше статей по ES6 особенно по новым методам (такими как findIndex) и особеностями работы с массивами.
И в статье про map и set хотелось бы увидеть больше практических примеров в виде сравнения реализаций обычным способом и с использованием map или set. Что бы явно увидеть практические преимущества.

Спасибо.

**Comment by iliakan** [comment]
Да, я в настоящий момент готовлю новый релиз учебника на ES6. Соответственно, в нём это уже в порядке вещей будет.

**Comment by iliakan** [comment]
Спасибо.
