### ISSUE TITLE
Side-Navigation: incorrect HTML character "&gt;" instead of ">"

### ISSUE THREAD

**Issue by qetr1ck-op** [iliakan/javascript-tutorial#231]
![error sub nav](https://cloud.githubusercontent.com/assets/5235395/12207988/a8424652-b652-11e5-820b-f86c6a4207f9.png)

I've tried to figure out where it can be converted/decoded in source. But without success =(.

**Comment by iliakan** [comment]
Yeah, one-line fix if you know where.
