### ISSUE TITLE
«Замыкания, функции изнутри», неточности

### ISSUE THREAD

**Issue by igoradamenko** [iliakan/javascript-tutorial#232]
В первом примере, в подсвеченной строчке кода (http://learn.javascript.ru/closures), думаю, ошибка. Или же я неверно трактую назначение объекта `LexicalEnvironment`. Думаю, что на стадии инициализации `name` тоже должен быть `undefined`.

**Comment by igoradamenko** [comment]
Там же, но ниже, не распарсилась ссылка на статью в википедии про замыкания (тут: http://learn.javascript.ru/closures#итого-замыкания)

**Comment by iliakan** [comment]
Спасибо, исправил. По смыслу там всё верно, хотя надо бы и обновить под ES6 ;)

**Comment by igoradamenko** [comment]
@iliakan Значит всё же я неправильно понял, как заполняется `LexicalEnvironment` и почему **до** выполнения кода там появляется значение у `name`. Ведь с таким же успехом ниже могли бы быть сразу два вызова функции, и каким тогда будет значение `name`? Непонятно :)

Может стоит как-то пояснить там этот момент или отослать в нужное место стандарта? К слову, да, под ES6 надо обновить, ибо как минимум в инфоблоке «Тонкости спецификации» идёт отсылка к не тем секциям ECMA-262.

**Comment by igoradamenko** [comment]
@iliakan Прошу прощения. Прочитал комментарии, увидел таких же как я, осознал, что перечитывая пропускал «При вызове функции:». Теперь всё встало на свои места. Вы были правы.

Спасибо! :)
