### ISSUE TITLE
Невыполнимая задача

### ISSUE THREAD

**Issue by ba2095** [iliakan/javascript-tutorial#247]
В задаче 2 в главе про тестирование: https://learn.javascript.ru/testing#tasks в решении и самой задаче код в песочнице различается. А именно, по ссылке на песочницу для решения в файле index.html отсутствует 15 строка ```javascript if (n == 0 && x == 0) return NaN;```, что делает невыполнимым условие задания `ноль в нулевой степени даёт NaN` - тест не будет работать, если не править код функции, что не является целью данной задачи.
А что еще хуже, можно подумать, что автор сам не пишет тесты. :wink:

**Comment by iliakan** [comment]
Не могли бы уточнить.
Правильно ли я понял, что суть issue - в том, что в песочнице отсутствует одна эта строка кода, и её нужно добавить?

**Comment by ba2095** [comment]
Да, все верно. Эта строчка кода отсутствует в песочнице для решения и ее необходимо добавить.

**Comment by iliakan** [comment]
В условии предлагается исправить функцию `pow`, сделал это предложение более явным.
