### ISSUE TITLE
[Feature Request] Учебник в EPUB/PDF

### ISSUE THREAD

**Issue by ba2095** [iliakan/javascript-tutorial#248]
При покупке учебника в EPUB/PDF на указанный адрес электронной почты приходит письмо с возможностью скачать учебник по ссылке. Это конечно здорово, НО:

* При потере файлов/удалении письма, честно купивший учебник человек его теряет. (Вариант с личным обращением к автору не рассматриваю, не самый удобный для обоих.:smile:)
* Учебник все же содержит ошибки/опечатки, которые хоть и исправляются, остаются у тех, кто читает купленный учебник(но не он-лайн версию). Как-то даже обидно.:sob:

Принимая во внимание эти факторы, разумная(ИМХО) просьба включить раздел с актуальной EPUB/PDF версией учебника в меню аккаунта на сайте. Естественно, для честно купивших учебник. Аналогично разделу "Курсы".

**Comment by iliakan** [comment]
@ba2095:

1) Вообще, потеря файла происходит редко. Но я сильно увеличил срок действия ссылки.
2) По обновлению купленного учебника - это уже подписка выходит, другая реализация, да и смысл другой. 

В разделе Курсы есть материалы по пройденному курсу.
