### ISSUE TITLE
Координата x в задаче с героями

### ISSUE THREAD

**Issue by NikolayGorev** [iliakan/javascript-tutorial#261]
В задаче http://learn.javascript.ru/task/drag-heroes в решении http://plnkr.co/edit/Ug9iqb7sLEAqyD77bjPr?p=preview в 91 и 92 строках, по-моему, вместо dragElement.offsetHeight нужно брать dragElement.offsetWidth. 

~~~
if (newX > document.documentElement.clientWidth - dragElement.offsetHeight) {
    newX = document.documentElement.clientWidth - dragElement.offsetHeight;
}
~~~

Хоть ширина и высота картинок героев почти одинаковы, и разница заметна не будет, на мой взгляд логичнее для координаты x использовать ширину.

**Comment by iliakan** [comment]
fixed thanks!
