### ISSUE TITLE
Неправильный пример

### ISSUE THREAD

**Issue by Mustang98** [iliakan/javascript-tutorial#263]
На этой странице https://learn.javascript.ru/decorators пример декоратор-таймер неправильно работает на рекурсивных функциях. Ведь мы переопределили fibonacci в декоратор, и при каждом рекурсивном вызове запускается новый таймер, при этом внешний таймер работать не перестает. В результате получается, что множество таймеров работают одновременно, а потом складываются.
В этом же можно убедиться, добавив внешний таймер вокруг вызова fibonacci.
(строки 32-38) тут http://plnkr.co/edit/tuIBmyT7zJrM0h708lCm?p=preview

Решить проблему можно, используя именованное функциональное выражение для рекурсии, а переопределять в декоратор внешнее название, т.е. только первый вызов.

**Comment by iliakan** [comment]
Да, проблема интересная, такой декоратор должен корректно работать на любых функциях, нет только на функциональных выражениях.

Как бы его исправить?

**Comment by Mustang98** [comment]
Можно обертку назвать по-другому, например `wrap_fibonacci = timingDecorator(fibonacci, "fibo");`, не переопределяя исходную функцию. Иначе вряд ли что-то можно придумать, ведь исходное имя используется внутри.

**Comment by iliakan** [comment]
Сделал пока через NFE, посмотрим будут ли непонятки.
