### ISSUE TITLE
Методы объектов, this - Значение this в объявлении объекта

### ISSUE THREAD

**Issue by voidshah** [iliakan/javascript-tutorial#265]
в задании здесь
https://learn.javascript.ru/object-methods#%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-this-%D0%B2-%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B8-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%B0
глобальная переменная firstName как раз определена
`var firstName = "";`
поэтому в решении здесь
https://github.com/iliakan/javascript-tutorial/blob/ru/1-js/6-objects-more/1-object-methods/4-object-property-this/solution.md
ответ будет не **undefined**, а пустая строка.

**Comment by Mustang98** [comment]
А вы хоть запускали код из решения? Ведь там выводится не просто export.firstName, а user.export.firstName, а т.к. export=this=window, то получается, что выводится **user.window.firstName**, a в объекте user свойства window нет. Поэтому и undefined.

**Comment by voidshah** [comment]
К вам такой же встречный вопрос. Потому как у себя локально вы точно не запускали этот код. Скопируйте пример и посмотрите в отладчике. А я так просто написал))).
Конечно запускал у себя на машине и получил пустую строку и понятно почему. Просто ваш ход мысли не верен.
Ведь объясняется же в учебнике, что

> "Получается, что в строке (*) мы имеем export: window, так что далее alert(user.export.firstName) выводит свойство window.firstName, то есть глобальную переменную firstName, которая не определена."

т.е. в user.export  еще до запуска alert находится _**ссылка на глобальный объект**_ window, соответственно user.export фактически равно window, а так как firstName определена в глобальной области и имеет значение "", то и alert выведет пустую строку.
**_window - не свойство_**. Это глобальный объект.

**Comment by Mustang98** [comment]
Да, вынужден согласиться с вами, протупил что-то. Если запустить в консоле, выводится пустая строка. Однако запуская пример прям на сайте у меня действительно выводится undefined (Firefox), это и ввело меня в заблуждение.

**Comment by voidshah** [comment]
Зачем себя вынуждать?!)) Мы тут не за первенство боремся))) Главное, что разобрались!
Для того, чтобы вернулось _undefined_, надо изменить задачу хотя бы так:
`var firstName;`

**Comment by igoradamenko** [comment]
Чуть не создал подобный ишью :)

Так что просто — :+1:

**Comment by iliakan** [comment]
fixed thanks!
