### ISSUE TITLE
Перехват ошибок, "try..catch" - Задача Finally или просто код?

### ISSUE THREAD

**Issue by voidshah** [iliakan/javascript-tutorial#266]
В [решении]( https://github.com/iliakan/javascript-tutorial/blob/ru/1-js/7-js-misc/5-exception/1-finally-or-code-after/solution.md) есть такая фраза:

> Поведение будет различным, если управление каким-то образом выпрыгнет из try..catch.
> 
> Например, finally сработает после return:

```
function f() {
  try {
    ...
    return result;
  } catch (e) {
    ...
  } finally {
    очистить ресурсы
  }
}

```
Как так? может "finally сработает **до** return"

**Comment by iliakan** [comment]
fixed.
