### ISSUE TITLE
«Дескрипторы, геттеры и сеттеры свойств», ошибка

### ISSUE THREAD

**Issue by igoradamenko** [iliakan/javascript-tutorial#270]
Похоже, что в конце [урока](https://learn.javascript.ru/descriptors-getters-setters) есть ошибка. Пробую создать объект, вызываю `Object.isExtensible(obj)` — получаю `true`. Думаю (да и судя по названию), в описании ошибка:

> Object.isExtensible(obj), Object.isSealed(obj), Object.isFrozen(obj)
Возвращают `true`, если на объекте были вызваны методы `Object.preventExtensions/seal/freeze`.

Должно быть, наверное, как-то так:

> Object.isExtensible(obj)
Возвращает `true`, если на объекте **не был** вызван метод `Object.preventExtensions`.
> 
Object.isSealed(obj), Object.isFrozen(obj)
Возвращают `true`, если на объекте были вызваны методы `Object.seal/freeze`.

**Comment by iliakan** [comment]
right.
