### ISSUE TITLE
Битый код на странице

### ISSUE THREAD

**Issue by Mustang98** [iliakan/javascript-tutorial#282]
В этом блоке статьи http://learn.javascript.ru/metrics-window#window-scroll в 4й строке снизу не отобразилась кнопка (<button onclick="window.scrollBy(0,10)">window.scrollBy(0,10)</button>)

**Comment by slawiko** [comment]
@Mustang98 не удается воспроизвести. Могли бы вы поточнее описать? Какая конфигурация, какой браузер?

**Comment by Mustang98** [comment]
Только что проверил, уже все работает
