### ISSUE TITLE
[minor] Опечатка в слове

### ISSUE THREAD

**Issue by etnolover** [iliakan/javascript-tutorial#285]
"Примере выше" нужно исправить на "Пример выше".

Детали:
В параграфе "Конструктор" (https://learn.javascript.ru/constructor-new#конструктор) во врезке "new function() { … }" опечатка во втором абзаце ("Примере выше с тем же успехом можно было бы переписать как:").

![default](https://cloud.githubusercontent.com/assets/7853748/13374788/77560104-dd9f-11e5-9190-3026e2017366.png)

**Comment by iliakan** [comment]
Можно PR? :)

**Comment by iliakan** [comment]
(Если ещё не пофиксено)

**Comment by etnolover** [comment]
Илья, с удовольствием, если объясните мне, как увидеть это в коде:)
Я новичок, не разбираюсь в этом. Только погружаюсь в увлекательный мир)
26 марта 2016 г. 11:46 PM пользователь "Ilya Kantor" <
notifications@github.com> написал:
