### ISSUE TITLE
Ошибка в описании синтаксиса метода splice

### ISSUE THREAD

**Issue by alexkudrow** [iliakan/javascript-tutorial#298]
Синтаксис метода splice в статье указан таким:
````
arr.splice(index[, deleteCount, elem1, ..., elemN])
```
Но должно быть так:
````
arr.splice(index, deleteCount[, elem1, ..., elemN])
```
[MDN splice](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)

**Comment by iliakan** [comment]
Поправьте MDN. У меня всё верно. 

Вообще, на самом деле, синтаксис такой: `arr.splice([index, ....]). То есть, все аргументы необязательны, но без аргументов вызов не имеет смысла, поэтому мой вариант оставляю.
