### ISSUE TITLE
Изменение порядка параграфов

### ISSUE THREAD

**Issue by slawiko** [iliakan/javascript-tutorial#301]
Мне кажется необходимым поменять параграф [Функции](https://learn.javascript.ru/es-function) с параграфом [Строки](https://learn.javascript.ru/es-string) местами. Во-первых потому что в параграфе [Функции](https://learn.javascript.ru/es-function) используется синтаксис, который описывается в параграфе [Строки](https://learn.javascript.ru/es-string). Во-вторых это было бы правильно с точки зрения логики: сначала примитивы, потом объекты. 
Сделать pull request просто с изменением имени двух папок я могу, но боюсь, что это будет бессмысленно. Если все же есть смысл - пишите, я сделаю pull request ([ветку](https://github.com/slawiko/javascript-tutorial/tree/slawiko-patch-5) уже подготовил).

**Comment by iliakan** [comment]
Этот раздел подразумевает, что человек уже знает JavaScript. 
Но, конечно, это не правильно, я посмотрю. Можно цитату?

**Comment by slawiko** [comment]
Вот здесь используется строки-шаблоны
```javascript
function showMenu(title = "Без заголовка", width = 100, height = 200) {
  alert(`${title} ${width} ${height}`);
}
```
хотя что такое строки-шаблоны читатель еще не знает.
