### ISSUE TITLE
Mutator array methods list

### ISSUE THREAD

**Issue by iketari** [iliakan/javascript-tutorial#333]
При описании методов массива [здесь](https://learn.javascript.ru/array-methods#свой-порядок-сортировки) не указано явно, какой метод изменяет исходный массив, а какой создает новый массив.

С одной стороны вроде как можно догадаться из примеров, что с массивами происходит, но все же явно это не указывается, а это важно. Было бы приятно, если бы была добавлена еще одна классификация методов (например, в итог в конце главы): изменяют исходный массив, создают копию. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype#Mutator_methods

**Comment by iliakan** [comment]
done.
