### ISSUE TITLE
http://javascript.info/ is not working

### ISSUE THREAD

**Issue by nagarjunai** [iliakan/javascript-tutorial#341]
![javascript info not working](https://cloud.githubusercontent.com/assets/5477552/15660095/b1a5118a-26f4-11e6-958a-0b19d698c6bd.png)

@iliakan javascript.info is a great site to learn javascript. Your knowledge is awesome and your explanation is simple, straight forward, very easy to understand. Daily i spend an hour in your site. For some reason the site is not working, it is throwing 404. Make sure to work it fine.

Thanks.

**Comment by iliakan** [comment]
Please check now?

**Comment by nagarjunai** [comment]
Working now. Thanks!
