### ISSUE TITLE
Ошибка на странице http://learn.javascript.ru/native-prototypes#примитивы

### ISSUE THREAD

**Issue by bedrosenator** [iliakan/javascript-tutorial#352]
// попытаемся записать свойство в строку:
var user = "Вася";
user.age = 30;

alert( user.age ); // undefined
Если нажать на кнопку "выполнить код", то вылетает ошибка
Если выполнить код в консоли - то всё нормально

http://joxi.ru/K823gLzTgXbd2O

**Comment by iliakan** [comment]
fixed.
