### ISSUE TITLE
Читать учебник с телефона - хардкор

### ISSUE THREAD

**Issue by Alexey-v-Ivanov** [iliakan/javascript-tutorial#36]
Это сугубо мое мнение, но попробуйте сами:

При пролистывании блока кода (из примеров) влево, если движение слишком быстрое, происходит переход на следующую страницу раздела (типа Alt + &rarr на десктопе).
В итоге, либо пролистывай "затаив дыхание", либо возвращайся по нескольку раз на предыдущую страницу и ищи место на котором остановился.

Откровенно говоря, это бесит)

**Comment by iliakan** [comment]
Хмм, как бы сделать? Свайп как способ листания - по идее, удобен.

**Comment by Alexey-v-Ivanov** [comment]
Моя первая идея была бы такая:
Сделать внизу экрана кнопку, которая перемещала пользователя к элементам навигации (вниз или вверх), откуда пользователь может перейти вперед или назад по учебнику.

Вторая идея:
Сделать навигацию внизу страницы: например, стрелочки с position: fixed;

Третья (основная):
Можно попробовать запретить переход свайпом, если свайп выполнен по блоку с кодом.
Это изящно и это решило бы проблему.

Как реализовать (мысль): если переход свайпом реализован через эвентлистенер, прикрученный к чему-то большому (боди или враппер/контейнер), то можно попробовать увеличить всем элементам c боковым скроллом z-index.

**Comment by tadjik1** [comment]
Может быть что-то вроде этого?

```javascript
var codeBlocks = document.querySelectorAll('.code-example');
var stopPropagationHandler = function (e) { e.stopPropagation(); };

[].forEach.call(codeBlocks, function (el) {
  onSwipe(el, {onRight: stopPropagationHandler, onLeft: stopPropagationHandler});
});
```

правда получится много обработчиков, и логичнее использовать делегирование. но я не знаю как его совместить с текущим решением, которое хендлит этот эвент на самом document.
можно слушать событие на контейнере.

**Comment by iliakan** [comment]
Можно если свайп по элементу с прокруткой, то не перелистывать.

**Comment by iliakan** [comment]
Сделано, будет выложено на следующем релизе (завтра?)
