### ISSUE TITLE
Не рабочая ссылка (Качество кода - Советы по стилю ) 

### ISSUE THREAD

**Issue by tsvetkovpro** [iliakan/javascript-tutorial#373]
В разделе учебника  https://learn.javascript.ru/coding-style#%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%B0-%D0%BF%D0%BE-%D1%81%D1%82%D0%B8%D0%BB%D1%8E - Качество кода -Советы по стилю кода

существует нерабочая ссылка на Google JavaScript Style Guide . Она никуда не ведёт : http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml

**Comment by iliakan** [comment]
Видимо, неактуально уже?
