### ISSUE TITLE
Несоответствие решения и теста в песочнице

### ISSUE THREAD

**Issue by edamov** [iliakan/javascript-tutorial#374]
В тесте в [песочнице](http://plnkr.co/edit/WNlhZdeL7jeeUBRYr7f9?p=preview) для задачи [Усечение строки](https://learn.javascript.ru/task/truncate) используется Unicode символ "&hellip;", а в решении три точки "...". Из-за этого при подстановке решения в песочницу, тесты падают.
Нужно исправить либо тест, либо решение.

**Comment by iliakan** [comment]
Вроде сейчас ок.
