### ISSUE TITLE
Ошибка(ES2015-Функции)

### ISSUE THREAD

**Issue by boddik** [iliakan/javascript-tutorial#384]
Доброго времени суток.
Обнаружил ошибку на странице  https://learn.javascript.ru/es-function.
в примере:
'use strict';

let getTime = () => {
  let date = new Date();
  let hours = date.getHours();
  let minutes = date.getMinutes();
  return hourse + ':' + minutes;              <----------------- hourse is not defined
};

alert( getTime() ); // текущее время

**Comment by slawiko** [comment]
Can be closed [commit](https://github.com/iliakan/javascript-tutorial/commit/e176535fe12d901911755eb54a1e42b7bb6108f8)
