### ISSUE TITLE
Две ссылки на одно решение в задаче

### ISSUE THREAD

**Issue by konstantin-agafonov** [iliakan/javascript-tutorial#39]
Две ссылки на одно решение в задаче http://learn.javascript.ru/introduction-browser-events#%D1%81%D0%BF%D1%80%D1%8F%D1%82%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%B8-%D0%BA%D0%BB%D0%B8%D0%BA%D0%B5

**Comment by iliakan** [comment]
fixed.
