### ISSUE TITLE
Опечатка в тексте

### ISSUE THREAD

**Issue by dimFora** [iliakan/javascript-tutorial#401]
Добрый день!

В тексте: С точки зрения стандарта это ошибка, но IE8- также включает в children узлы, соответствующие HTML-**комментариям**. опечатка. 
Правильно: С точки зрения стандарта это ошибка, но IE8- также включает в children узлы, соответствующие HTML-комментарии.

**Comment by slawiko** [comment]
@dimFora можно хотя бы ссылку на страницу с ошибкой?

**Comment by w3lifer** [comment]
@slawiko, Google, милый Google :) [тыц](https://google.com/search?q=С+точки+зрения+стандарта+это+ошибка,+но+IE8-+также+включает+в+children+узлы,) ...

**Comment by slawiko** [comment]
@w3lifer мне кажется стоило бы @dimFora изначально ссылку вставлять, дабы избежать лишних телодвижений с нашей стороны :) Все же как-то неправильно иначе

**Comment by dagolinuxoid** [comment]
@dimFora  нет, всё верно написано - С точки зрения стандарта это ошибка, но IE8- также включает в children узлы, соответствующие HTML-комментариям. Имеется ввиду children yзлы которые соответсвуют HTML-комментариЯМ имхо. Закрывайте issue. PS. IE8 уже не особо релевантен тем более :)
