### ISSUE TITLE
Ошибка в примере. https://learn.javascript.ru/variables

### ISSUE THREAD

**Issue by MakarovS96** [iliakan/javascript-tutorial#402]
Во втором примере, где указывается местоположение 'use strict', ошибка при запуске всё равно показывается.
![image](https://cloud.githubusercontent.com/assets/19629483/18914727/fdfcb848-8596-11e6-9edb-c249220ffe3c.png)
Браузер Mozilla Firefox 49.0

**Comment by slawiko** [comment]
@MakarovS96 в следующий раз лучше сразу бы ссылку на страницу. [Вот так](https://learn.javascript.ru/variables#важность-директивы-var) например)

**Comment by kutovova** [comment]
Тоже хотел зарепортить.
Переменная создается без var вновь после употребления "use strict", как и в предыдущем примере. Хотя по логике повествования "use strict" с комментарием «// слишком поздно» должен идти после объявления переменной.

**Comment by iliakan** [comment]
make PR please :)
