### ISSUE TITLE
https://javascript.info is down? Error 522

### ISSUE THREAD

**Issue by JeffKang** [iliakan/javascript-tutorial#405]
https://javascript.info is down? 
Error 522 Ray ID: 2f609ff829862a97 • 2016-10-22 23:11:04 UTC
This site was a great resource.

>because the site uses CloudFlare's Always Online™ technology you can continue to surf a snapshot of the site

I didn't see that before.
Maybe I can use the snapshots for now.

**Comment by iliakan** [comment]
guess fixed? thanks!
