### ISSUE TITLE
Ошибка в вёрстке статьи

### ISSUE THREAD

**Issue by mcmimik** [iliakan/javascript-tutorial#410]
https://github.com/iliakan/javascript-tutorial/blob/ru/1-js/4-data-structures/11-datetime/article.md

Начиная со строки:
`toUTCString()`
сбито форматирование, в исходниках вместо двоеточия в начале строки — «То же самое, что `toString()`, но дата в зоне UTC.» — прямо используются теги `<dl>` и др.

**Comment by slawiko** [comment]
Поправил в #418
