### ISSUE TITLE
Вход через github 

### ISSUE THREAD

**Issue by monochromer** [iliakan/javascript-tutorial#412]
Если входить через аккаунт github, то появляется ошибка:
![image](https://cloud.githubusercontent.com/assets/6412192/19895464/b55a237c-a072-11e6-8db4-0497f4206914.png)

При этом в профиле на github сайт learn.javascript.ru авторизован:
![image](https://cloud.githubusercontent.com/assets/6412192/19895519/e754a262-a072-11e6-96d5-ef0a6b3034ae.png)

**Comment by travis-javascript** [comment]
Может email не передали?

---
Best Regards,
Ilya Kantor

2016-11-01 18:37 GMT+03:00 monochromer <notifications@github.com>:

**Comment by monochromer** [comment]
Прошел обычную регистрацию, потом привязал аккаунт.
