### ISSUE TITLE
С мобильного не видно проблему, которую должен иллюстрировать пример

### ISSUE THREAD

**Issue by vityas-off** [iliakan/javascript-tutorial#430]
https://learn.javascript.ru/float#очистка-под-float
Так как текста возле картинки с винни пухом больше, чем высота дива с картинкой, все выглядит абсолютно нормально и проблема с демонстрацией необходимости clearfix не видна.
![screenshot_20161215-094532](https://cloud.githubusercontent.com/assets/15840124/21215931/b3aa901e-c2ac-11e6-9f70-ad2634fccf19.png)

**Comment by iliakan** [comment]
Да, специфика верстки такая :/ Понятно что при очень узком экране не будет видно.
