### ISSUE TITLE
Упрошенный синтаксис путает. 

### ISSUE THREAD

**Issue by pipols** [iliakan/javascript-tutorial#437]
https://learn.javascript.ru/function-declaration-expression#анонимные-функции

function ask(question, yes, no) {
    if (confirm(question)) yes()
    else no();
  }

Поменяйте пожалуйста на такой синтаксис. Я только учусь и меня ваш пример запутал. Сокращениям лучше учить в конце. Спасибо. 

function ask(question, yes, no) {
    if (confirm(question)) {
        yes();
    } else {
        no();
    }
}

**Comment by iliakan** [comment]
Наоборот полезно, разобрались как раз.
