### ISSUE TITLE
Шпаргалка для запоминания перебирающих методов массива

### ISSUE THREAD

**Issue by Sigizmund2012** [iliakan/javascript-tutorial#440]
Отличная шпаргалка по методам, перебирающим массив( на английском ) https://gist.github.com/ljharb/58faf1cfcb4e6808f74aae4ef7944cff
А ещё мне понравился способ запоминания аргументов для коллбека из комментариев: "My preferred mnemonic for the order of the callback arguments is "Element, Index, Container", because EIC is the first three letters of Brendan EICH."

Может что-то подобное сделать на русском в разделе о методах массива? https://learn.javascript.ru/array-methods

**Comment by iliakan** [comment]
Может быть, в виде графики какой-то файл или как-то еще короче. Что именно нужно от cheatsheet? Список методов краткий? Аргументы?
