### ISSUE TITLE
Создание объектов через "new"

### ISSUE THREAD

**Issue by dagolinuxoid** [iliakan/javascript-tutorial#445]
Детальнее – функция, запущенная через new, делает следующее: (original)
1. Создаётся новый пустой объект.
2. Ключевое слово this получает ссылку на этот объект.
3. Функция выполняется. Как правило, она модифицирует this, добавляет методы, свойства.
4. Возвращается this.
---
Детальнее – функция, запущенная через new, делает следующее: (custom)
1. Создаётся новый пустой объект.
2. Ключевое слово this получает ссылку на этот объект.
3. Функция выполняется. Как правило, она изменяет этот пустой вновь созданный объект, добавляя ему свойства/методы.
4. Возвращается уже измененный(модифицированный) объект.
---
Я добавил своё видение в issues  а не напрямую сделал PR, потому что с одной стороны считаю, что это более точно, но не уверен, что мой черновой вариант более предпочтителен для читателя.
Главный подвох в фразе [модифицирует this], которую знающие уже прочитают как именно изменения нового объекта, а свежие люди могут подумать под этим сочетанием, что this можно изменять во время исполнения кода после 'точки входа' так сказать, что конечно же не верно - this - неизменяемо в JS во время рантайма ибо не является переменной. Я могу крепко заблуждаться насчет своих выводов и с нетерпением буду ожидать ответа, спасибо :).

**Comment by iliakan** [comment]
добавил пояснение
