### ISSUE TITLE
Не совсем верно работающий пример

### ISSUE THREAD

**Issue by slawiko** [iliakan/javascript-tutorial#447]
https://github.com/iliakan/javascript-tutorial/blob/ru/2-ui/2-events-and-interfaces/4-event-bubbling/bubble-target.view/script.js - этот пример не подсвечивает желтым элементы, как это написано в коде. 

http://learn.javascript.ru/event-bubbling#целевой-элемент-event-target - ссылка на статью

**Comment by iliakan** [comment]
А что именно там должно подсвечиваться?
