### ISSUE TITLE
Отсылки к IE10- и IE8-

### ISSUE THREAD

**Issue by pwa54rus** [iliakan/javascript-tutorial#450]
Пожалуй в каждом уроке есть отсылки к работе того или иного кода в IE. Очевидно, что эти отсылки морально устарели т.к. сам IE уже четыре года как не поддерживается. И доля кода написанного с учетом особенностей IE, и доля пользователей IE ничтожна. Может пора уже отказаться от этих отсылок и не перегружать учебник ненужной информацией?

**Comment by cherniavskii** [comment]
@pwa54rus Тем не менее некоторые проекты поддерживают IE10-. Считаю, что полезно иметь понятие, какие подводные камни есть в IE и как их обойти. Тем более, что всегда можно такую секцию пропустить - я в большинстве случаев так и делаю.

**Comment by iliakan** [comment]
Пропускайте IE10-, если вам не нужно
