### ISSUE TITLE
Promise

### ISSUE THREAD

**Issue by Kapiroska** [iliakan/javascript-tutorial#462]
> Обратим внимание, что последний then в нашем примере ничего не возвращает. Если мы хотим, чтобы после setTimeout (*) асинхронная цепочка могла быть продолжена, то последний then тоже должен вернуть промис. Это общее правило: если внутри then стартует новый асинхронный процесс, то для того, чтобы оставшаяся часть цепочки выполнилась после его окончания, мы должны вернуть промис.

Для того,  чтобы оставшаяся часть цепочки выполнилась после окончания асинхронного запроса, не обязательно возвращать промис. Она и так выполнится. Просто будет невозможно получить результат работы этого промиса.

**Comment by iliakan** [comment]
Да, здесь имеется в виду *после его окончания*
