### ISSUE TITLE
Ошибка в решении задачи

### ISSUE THREAD

**Issue by zablotski** [iliakan/javascript-tutorial#475]
Добрый день, 

В нижеупомянутом решении есть ошибка. Код будет выводить `0` в случае, если пользователь введет любой стринг не число(который преобразуется в `NaN`) отрабоатет последний `else`.
A  в соответствии с заданием `0` выводится если пользователь вводит `0`.

Скрин ниже
![image](https://cloud.githubusercontent.com/assets/3640624/24335447/ef03a756-127d-11e7-8b1e-589734f011cc.png)

**Comment by iliakan** [comment]
Там предполагается, что вводится число =)
