### ISSUE TITLE
Debugging in chrome - chapter 3.1

### ISSUE THREAD

**Issue by filipmor** [iliakan/javascript-tutorial#479]
Hi Iliakan!

In chapter 3.1 you describe the behaviour of chrome debugger on an example of two files: index.html and hello.js. However they are not visible anywhere in the Sources tree.
![missing_files](https://cloud.githubusercontent.com/assets/11389988/24378951/2a9ca570-1345-11e7-95ce-79d8874c76e7.PNG)

Anyway, really great job!
Best wishes,
Filip

**Comment by iliakan** [comment]
Added explanations.
