### ISSUE TITLE
В примере в input'е нет автоскролла

### ISSUE THREAD

**Issue by konstantin-agafonov** [iliakan/javascript-tutorial#51]
http://learn.javascript.ru/mousemove-mouseover-mouseout-mouseenter-mouseleave#%D0%B4%D0%B5%D0%BB%D0%B5%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5

**Comment by CustomButtons** [comment]
Pull request [#66](https://github.com/iliakan/javascript-tutorial/pull/66)

**Comment by iliakan** [comment]
Имеется в виду первый пример в разделе Делегирование? http://learn.javascript.ru/mousemove-mouseover-mouseout-mouseenter-mouseleave#%D0%B4%D0%B5%D0%BB%D0%B5%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5

@CustomButtons - твой PR тоже про этот конкретный пример?
