### ISSUE TITLE
Не совсем верно работающий пример #2

### ISSUE THREAD

**Issue by borm** [iliakan/javascript-tutorial#523]
[https://learn.javascript.ru/recursion#вычислить-сумму-чисел-до-данного](url)

В задаче сказано 
sumTo(4) = 4 + 3 + 2 + 1 = 10

Решение с использованием цикла:
```
function sumTo(n) {
  var sum = 0;
  for (var i = 1; i <= n; i++) {
    sum += i;
  }
  return sum;
}

alert( sumTo(100) );
```
Ваш пример решения увеличивает "i" на +1, то есть
1 + 2 + 3 + 4 = 10

Правильно будет
```
function sumTo(n) {
  var sum = 0;
  for ( var i = n; i>=1 ; i--) {
    sum += i;
  }
  return sum;
}
```

**Comment by iliakan** [comment]
В моем примере sum(4) = 10, т.е считает верно. Не понятно, где ошибка?

**Comment by borm** [comment]
Считает верно, но нужно добавлять числа не по возрастанию а по убыванию
