### ISSUE TITLE
contribution rules

### ISSUE THREAD

**Issue by parmentelat** [iliakan/javascript-tutorial#548]
Hi there

I started to read this very nice and helpful resource on javascript.info, and then realized it was on github, so I made a fork and started to record in there the typos and other improvements I could suggest.

Are there any specific rules I should follow for submitting this ? 
One of the things is, as far as typos go, it's straightforward;
but for example for code addition, I think I got how the framework works approximately, but I am not exactly able to test that stuff..

Please advise

and in any case  many thanks for that very helpful piece of work !!

**Comment by iliakan** [comment]
Please submit fixes using PRs as you do them. Don't wait till you have a lot, just push them when they are ready.

If you're going to write a lot of good things, I can prepare local tutorial server for you.
