### ISSUE TITLE
coding styles, automated style linters : duplication

### ISSUE THREAD

**Issue by parmentelat** [iliakan/javascript-tutorial#549]
hi again

I'm not quite sure how to fix this myself, but I am finding that the sections on
* coding styles, and
* automated style linters

are kind of duplicated in both
* `1-js/03-code-quality/02-coding-style/article.md`
* `1-js/03-code-quality/03-comments/article.md`

it does not seem to be intentional, is it ?

**Comment by iliakan** [comment]
Right, I'll review and fix that.
