### ISSUE TITLE
7 types, 6 of which are "primitive" ?

### ISSUE THREAD

**Issue by parmentelat** [iliakan/javascript-tutorial#552]
At the very beginning of the Objects chapter here https://javascript.info/object, it is said:

> As we know, there are 7 language types in JavaScript. Six of them are called “primitive”, because their values contain only a single thing (be it a string or a number or whatever).

I may have missed that part, but I could not figure out what previous part in the tutorial is referred to with this *"As we know"* part, and in any case it would definitely help to give the complete list again at that point IMHO.

**Comment by iliakan** [comment]
Added the link.
