### ISSUE TITLE
sort() and reverse() on arrays

### ISSUE THREAD

**Issue by parmentelat** [iliakan/javascript-tutorial#557]
In the chapter on array methods https://javascript.info/array-methods:

 * it is said in https://javascript.info/array-methods#sort-fn that `sort()` sorts the `Array` object in place,
* and in https://javascript.info/array-methods#reverse it is said that `reverse()` creates a new array

It did not sound right that both methods would behave differently in this respect; and indeed as far as I can tell, the latter is wrong, and `reverse()` actually does its job in place too.

**Comment by iliakan** [comment]
Right!
