### ISSUE TITLE
node seems to handle

### ISSUE THREAD

**Issue by parmentelat** [iliakan/javascript-tutorial#562]
in the first article on object properties, I was running the examples under node and found that unlike the browser, it did not throw an error; the property indeed is not assigned, but no exception was thrown either

```
> obj = { 'a' : 1 }
{ a: 1 }
> Object.defineProperty(obj, 'a', {'writable' : false})
{ a: 1 }
> Object.getOwnPropertyDescriptor(obj, 'a')
{ value: 1,
  writable: false,
  enumerable: true,
  configurable: true }
> obj.a = 2
2
> obj.a
1
```

**Comment by parmentelat** [comment]
a little later down the road, there is a note about "use strict"; at first I thought that was what I was seeing.
So I tried again in strict mode, but the behaviour is the same

```
$ node
> "use strict"
'use strict'
> o = {'a' : 1}
{ a: 1 }
> Object.defineProperty(o, 'a', {'writable' : false })
{ a: 1 }
> o.a=2
2
```

Am I doing something wrong ?

**Comment by iliakan** [comment]
You run statements one by one, separately, so `use strict` does not affect the statements below. 

In particular, you could assign to an undeclared variable `o`, normally an error in strict mode.

Instead, please put the code into a separate file like `my.js`:
```
'use strict'
let o = {'a' : 1}
Object.defineProperty(o, 'a', {'writable' : false })
o.a=2
```

...And then run it:

```
iliakan> node 1.js
/Users/iliakan/1.js:4
o.a=2
   ^

TypeError: Cannot assign to read only property 'a' of object '#<Object>'
    at Object.<anonymous> (/Users/iliakan/1.js:4:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```
