### ISSUE TITLE
Babel

### ISSUE THREAD

**Issue by hzoo** [iliakan/javascript-tutorial#589]
Looking at https://github.com/iliakan/javascript-tutorial/blob/en/1-js/03-code-quality/06-polyfills/article.md#babeljs, I can provide some suggestions (as a maintainer).

`Babel.JS` -> just `Babel`? I think the only time we use the js is for our [twitter](https://twitter.com/babeljs).

Regarding modern engines and transpiling, I would probably mention https://github.com/babel/babel-preset-env which we made to only compile what is necessary (and this includes babel-polyfill)

**Comment by iliakan** [comment]
Fixed thanks.
