### ISSUE TITLE
Текст заголовка

### ISSUE THREAD

**Issue by konstantin-agafonov** [iliakan/javascript-tutorial#6]
http://learn.javascript.ru/closures-module#%D1%8D%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-return

Здесь логичнее будет смотреться слово Экспорт вместо Экспортирование

**Comment by iliakan** [comment]
Ок
