### ISSUE TITLE
Таблицы совместимости

### ISSUE THREAD

**Issue by burashka** [iliakan/javascript-tutorial#82]
В разделе про ES2015 может стоит сделать в конце описания каждой фичи таблицу поддержки браузерами, как это в MDN? ES6-таблица (http://kangax.github.io/compat-table/es6/) это здорово, но часто сложно сопоставить фичу с англоязычной терминологией и понять какая строка в таблице мне нужна. Или хотя бы давать прямую ссылку на конкретную строку в таблице (она так, к счастью, умеет).

**Comment by iliakan** [comment]
Это все меняется, я не смогу поддерживать такое.
