### ISSUE TITLE
Нет решения в задаче

### ISSUE THREAD

**Issue by tehkonst** [iliakan/javascript-tutorial#96]
https://learn.javascript.ru/task/coffeemachine-disable-stop
В этой задаче вместо решения ссылка.

**Comment by iliakan** [comment]
Там ссылка вроде на решение, нет?

**Comment by tehkonst** [comment]
Да, извините. Показалось сначала, что решение от другой задачи.
Потому что в концовке там нет этого:
```javascript
  var coffeeMachine = new CoffeeMachine(10000);
  coffeeMachine.enable();
  coffeeMachine.run();
  coffeeMachine.disable(); // остановит работу, ничего не выведет
```
и соответственно в консоли выводилось не то, что ожидается

Да и планкер этот два дня не грузился.
